name: Update GitHub Pages

on:
    push:
      branches:
        - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  update-gh-pages:
    permissions:
      contents: "write"
    name: Update GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build mock application
        run: npm run build
      - name: Update GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
